export const page = `<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>我的南京大学校园码</title>
<style>
:root{color-scheme:light;font-family:system-ui,sans-serif;color:#302735;background:#f6f3f8}*{box-sizing:border-box}body{margin:0;padding:40px 18px}main{max-width:420px;margin:auto}h1{font-size:25px;margin:0 0 10px}.intro{color:#746879;font-size:14px;line-height:1.7}.card{background:white;border-radius:22px;padding:25px;margin-top:24px;box-shadow:0 8px 40px #3b17450a}label{display:block;margin-bottom:8px}input{width:100%;font:inherit;padding:13px;border:1px solid #d8cedc;border-radius:10px}button{font:inherit;border:0;background:#881c81;color:white;border-radius:12px;padding:13px 20px;cursor:pointer}form button{width:100%;margin-top:16px}button:disabled{opacity:.5}#code{display:block;width:100%;aspect-ratio:1;image-rendering:pixelated;background:white}#qr[hidden],#code[hidden],section[hidden]{display:none}.actions{display:flex;gap:10px;margin-top:18px;justify-content:center}.secondary{background:#f1ebf4;color:#6b476f}#status{min-height:42px;line-height:1.6;font-size:14px;color:#746879;text-align:center;margin:15px 0 0}#time{text-align:center;font-size:15px;font-variant-numeric:tabular-nums}.error{color:#b32e45!important}footer{margin:20px 0;text-align:center;font-size:12px;color:#8a7c91}input:focus-visible,button:focus-visible{outline:3px solid #ba88c9;outline-offset:3px}
footer a{color:#6b476f;overflow-wrap:anywhere}
</style></head><body><main><h1>我的校园码</h1><p class="intro">南京大学 · 消费 / 通行<br>实时刷新，密码访问。</p>
<section class="card" id="login"><form id="form"><label for="password">访问密码</label><input id="password" type="password" autocomplete="current-password" required maxlength="128"><button id="submit">查看校园码</button></form></section>
<section class="card" id="qr" hidden><p id="time"></p><img id="code" alt="当前校园码" hidden><p id="status" role="status" aria-live="polite">正在获取校园码…</p><div class="actions"><button id="refresh">立即刷新</button><button id="logout" class="secondary">锁定</button></div><div class="actions"><button id="authorize" class="secondary">用南京大学 APP 登录 / 重新授权</button></div></section>
<section class="card" id="authorization" hidden><h2 style="font-size:20px;margin-top:0">南京大学 APP 授权</h2><p class="intro">用已登录的南京大学 APP「扫一扫」，扫描后在手机确认登录。首次登录绑定账号，后续授权使用同一账号。</p><img id="authorizeImage" alt="南京大学官方登录授权二维码" style="width:100%;image-rendering:pixelated" hidden><p id="authorizeMsg" role="status" aria-live="polite"></p><button id="authorizeClose" class="secondary">关闭</button></section>
<p id="loginError" class="error" role="alert"></p><footer>二维码与页面均不缓存<br>本页面部署自 GitHub 仓库：<a href="https://github.com/yama-lei/nju-qrcode-on-cloudflare" target="_blank" rel="noopener noreferrer">yama-lei/nju-qrcode-on-cloudflare</a></footer></main>
<script>
const byId=id=>document.getElementById(id);let timer,expiryTimer,busy=false,generation=0,authTimer,authGeneration=0;
async function api(path,body){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body||{}),cache:'no-store',signal:AbortSignal.timeout(45000)});let data=await r.json();if(!r.ok){const e=new Error(data.error||'请求失败');e.status=r.status;throw e}return data}
function clearCode(){byId('code').hidden=true;byId('code').removeAttribute('src');byId('time').textContent=''}
function cancelAuthorization(){authGeneration++;clearTimeout(authTimer);byId('authorization').hidden=true;byId('authorizeImage').hidden=true;byId('authorizeImage').removeAttribute('src');byId('authorize').disabled=false}
function lock(){generation++;clearTimeout(timer);clearTimeout(expiryTimer);clearCode();cancelAuthorization();byId('login').hidden=false;byId('qr').hidden=true}
async function refresh(){if(busy)return;busy=true;const current=generation;clearTimeout(timer);byId('refresh').disabled=true;
try{const started=performance.now();const d=await api('/api/code');if(current!==generation)return;const remaining=d.displayUntil-d.issuedAt-(performance.now()-started);if(remaining<=0)throw new Error('取码超时，请重新刷新');
clearTimeout(expiryTimer);byId('code').src=d.image;byId('code').hidden=false;byId('time').textContent=d.timestamp;byId('status').classList.remove('error');byId('status').textContent='已更新 · 每 25 秒自动刷新';
expiryTimer=setTimeout(()=>{clearCode();byId('status').textContent='正在更新校园码…'},remaining);timer=setTimeout(refresh,Math.min(25000,remaining-2000));
}catch(e){if(current!==generation)return;clearCode();byId('status').classList.add('error');byId('status').textContent=e.message;if(e.status===401){lock();byId('loginError').textContent='请重新输入访问密码'}else if(e.status!==428)timer=setTimeout(refresh,5000)
}finally{busy=false;byId('refresh').disabled=false}}
function show(){byId('login').hidden=true;byId('qr').hidden=false;byId('loginError').textContent='';refresh()}
byId('form').onsubmit=async e=>{e.preventDefault();byId('submit').disabled=true;try{await api('/api/login',{password:byId('password').value});byId('password').value='';show()}catch(e){byId('loginError').textContent=e.message}finally{byId('submit').disabled=false}};
byId('refresh').onclick=refresh;byId('logout').onclick=async()=>{lock();await api('/api/logout').catch(()=>{})};
byId('authorizeClose').onclick=cancelAuthorization;
byId('authorize').onclick=async()=>{cancelAuthorization();const current=authGeneration;byId('authorize').disabled=true;byId('authorization').hidden=false;byId('authorizeMsg').textContent='正在生成官方登录二维码…';try{const d=await api('/api/authorize/start');if(current!==authGeneration)return;byId('authorizeImage').src=d.image;byId('authorizeImage').hidden=false;byId('authorizeMsg').textContent='等待 APP 扫码并确认登录';byId('authorization').scrollIntoView({behavior:'smooth',block:'center'});pollAuthorization(current)}catch(e){if(current!==authGeneration)return;byId('authorizeMsg').textContent=e.message;byId('authorize').disabled=false}};
async function pollAuthorization(current){try{const d=await api('/api/authorize/status');if(current!==authGeneration)return;if(d.status==='authorized'){byId('authorizeMsg').textContent='授权成功，正在更新校园码';setTimeout(()=>{if(current!==authGeneration)return;cancelAuthorization();refresh()},800);return}if(d.status==='expired'){byId('authorizeMsg').textContent='授权二维码已过期，请关闭后重新点击登录';byId('authorizeImage').hidden=true;byId('authorize').disabled=false;return}byId('authorizeMsg').textContent=d.status==='scanned'?'已扫描，请在手机确认登录':'等待 APP 扫码并确认登录';authTimer=setTimeout(()=>pollAuthorization(current),2000)}catch(e){if(current!==authGeneration)return;byId('authorizeMsg').textContent=e.message;byId('authorize').disabled=false}}
document.addEventListener('visibilitychange',()=>{if(document.hidden){clearTimeout(timer);clearCode()}else if(!byId('qr').hidden)refresh()});
window.addEventListener('pageshow',()=>{clearCode();if(!byId('qr').hidden)refresh()});
api('/api/session').then(show).catch(()=>{});
</script></body></html>`;
